version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/ecommerce_dashboard
      - API_V1_STR=/api/v1
      - PROJECT_NAME=E-commerce Admin Dashboard API
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ecommerce_dashboard
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
